server:
  port: 8888
spring:
  application:
    name: theus-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/theuslinor/theus-config-server
          #username:
          #password:
          default-label: main
          search-paths:
            - 'greeting-service*'